import React, { useEffect, useState } from 'react';
import type { User } from 'firebase/auth';
import type { Category } from '../../types';
import { emptyResourceInput, type ResourceRecord } from '../../domain/resource';
import { getOwnedResourceRecords, requestResourceWithdrawal, saveContributorResource } from '../../services/canonicalResourceService';
import { changeContributorEmail, changeContributorPassword, updateContributorProfile } from '../../services/contributorAuthService';
import ResourceForm from '../resources/ResourceForm';

interface Props { user: User; categories: Category[]; initialScreen?: 'list' | 'create'; onLogout: () => Promise<void>; }
type Screen = 'list' | 'create' | 'edit' | 'account';
const label: Record<ResourceRecord['status'], string> = { pending_review: 'Pendiente de revisión', published: 'Publicado', rejected: 'Requiere corrección', withdrawal_requested: 'Retirada solicitada', archived: 'Retirado' };

const ContributorArea: React.FC<Props> = ({ user, categories, initialScreen = 'list', onLogout }) => {
  const [screen, setScreen] = useState<Screen>(initialScreen); const [records, setRecords] = useState<ResourceRecord[]>([]); const [selected, setSelected] = useState<ResourceRecord | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [name, setName] = useState(user.displayName || '');
  const load = async () => { setLoading(true); try { setRecords(await getOwnedResourceRecords(user.uid)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [user.uid]);
  useEffect(() => { setScreen(initialScreen); setSelected(null); }, [initialScreen]);
  const save = async (input: ReturnType<typeof emptyResourceInput>) => { const id = await saveContributorResource(input, selected?.id); setMessage(selected ? 'Cambios enviados de nuevo a revisión.' : 'Recurso enviado para revisión.'); setSelected(null); setScreen('list'); await load(); return id; };
  if (screen === 'create' || screen === 'edit') return <section className="panel max-w-3xl"><button className="link-button mb-4" onClick={() => { setScreen('list'); setSelected(null); }}>← Mis recursos</button><h2 className="text-2xl font-bold">{screen === 'create' ? 'Añade un recurso' : 'Edita tu recurso'}</h2><p className="mb-5 text-text-light">Lo revisará una persona voluntaria antes de publicarlo.</p><ResourceForm categories={categories} initialValue={selected || undefined} submitLabel="Enviar a revisión" onSubmit={save} onCancel={() => setScreen('list')} /></section>;
  if (screen === 'account') {
    const hasPassword = user.providerData.some((provider) => provider.providerId === 'password');
    return <section className="panel max-w-xl"><button className="link-button mb-4" onClick={() => setScreen('list')}>← Mis recursos</button><h2 className="text-2xl font-bold">Mi cuenta</h2><form className="mt-5 space-y-4" onSubmit={async (event) => { event.preventDefault(); await updateContributorProfile(user, name); setMessage('Datos actualizados.'); }}><label className="form-label">Nombre<input className="form-control" value={name} onChange={(e) => setName(e.target.value)} required /></label><label className="form-label">Correo electrónico<input className="form-control" value={user.email || ''} disabled /></label><button className="button-primary">Guardar datos</button></form><section className="mt-8 border-t border-gray-200 pt-5"><h3 className="text-lg font-bold">Seguridad</h3>{hasPassword ? <AccountSecurity user={user} onMessage={setMessage} /> : <p className="mt-2 text-sm text-text-light">Has accedido con Google. La contraseña y el correo se gestionan desde tu cuenta de Google.</p>}{hasPassword && !user.emailVerified && <p className="mt-3 text-sm text-amber-800">Tu correo todavía no está verificado. Revisa tu bandeja de entrada antes de solicitar cambios.</p>}</section><button className="link-button mt-8 text-red-700 dark:text-red-300" onClick={() => void onLogout()}>Cerrar sesión</button></section>;
  }
  return <section className="mx-auto max-w-4xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Tu colaboración</p><h2 className="text-3xl font-bold">Mis recursos</h2></div><div className="flex gap-2"><button className="button-secondary" onClick={() => setScreen('account')}>Mi cuenta</button><button className="button-primary" onClick={() => setScreen('create')}>+ Añade un recurso</button></div></div>{message && <p className="mb-4 rounded-xl bg-secondary p-3 text-sm text-primary-dark">{message}</p>}{loading ? <p>Cargando tus recursos…</p> : records.length === 0 ? <div className="panel text-center"><p className="text-lg font-semibold">Todavía no has enviado recursos.</p><p className="mt-2 text-text-light">Comparte un recurso útil para que Bokatas pueda revisarlo.</p></div> : <div className="space-y-3">{records.map((record) => <article key={record.id} className="panel flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap gap-2"><span className={`status-badge status-${record.status}`}>{label[record.status]}</span><span className="text-sm text-text-light">{record.createdAt.slice(0, 10)}</span></div><h3 className="mt-2 text-lg font-bold">{record.name}</h3><p className="text-sm text-text-light">{record.address}</p>{record.reviewComment && <p className="mt-2 text-sm">Mensaje de revisión: {record.reviewComment}</p>}</div><div className="flex gap-2"><button className="button-secondary" onClick={() => { setSelected(record); setScreen('edit'); }} disabled={!['pending_review', 'rejected'].includes(record.status)}>Editar</button>{record.status === 'published' && <button className="button-danger" onClick={async () => { await requestResourceWithdrawal(record.id); setMessage('La retirada queda pendiente de revisión.'); await load(); }}>Solicitar retirada</button>}</div></article>)}</div>}</section>;
};

const AccountSecurity: React.FC<{ user: User; onMessage: (message: string) => void }> = ({ user, onMessage }) => {
  const [currentPassword, setCurrentPassword] = useState(''); const [nextPassword, setNextPassword] = useState(''); const [nextEmail, setNextEmail] = useState(''); const [error, setError] = useState('');
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await changeContributorPassword(user, currentPassword, nextPassword); setCurrentPassword(''); setNextPassword(''); onMessage('Contraseña actualizada.'); } catch { setError('No se pudo cambiar la contraseña. Comprueba la contraseña actual.'); } };
  const changeEmail = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await changeContributorEmail(user, currentPassword, nextEmail); setCurrentPassword(''); setNextEmail(''); onMessage('Hemos enviado un enlace de verificación al nuevo correo. El cambio se aplicará al confirmarlo.'); } catch { setError('No se pudo iniciar el cambio de correo. Comprueba la contraseña actual.'); } };
  return <div className="mt-4 space-y-5"><form className="space-y-3" onSubmit={changePassword}><label className="form-label">Contraseña actual<input className="form-control" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required autoComplete="current-password" /></label><label className="form-label">Nueva contraseña<input className="form-control" type="password" value={nextPassword} onChange={(event) => setNextPassword(event.target.value)} required minLength={6} autoComplete="new-password" /></label><button className="button-secondary">Cambiar contraseña</button></form><form className="space-y-3" onSubmit={changeEmail}><label className="form-label">Nuevo correo electrónico<input className="form-control" type="email" value={nextEmail} onChange={(event) => setNextEmail(event.target.value)} required /></label><button className="link-button">Cambiar correo de forma segura</button></form>{error && <p className="text-sm text-red-700" role="alert">{error}</p>}</div>;
};
export default ContributorArea;
